# Generated by Django 4.2.3 on 2023-07-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(default='01'),
            preserve_default=False,
        ),
    ]
