# Generated by Django 4.2.3 on 2023-07-13 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_remove_persona_cedula_remove_persona_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prueba.persona')),
                ('numero', models.IntegerField()),
                ('posicion', models.CharField(max_length=50)),
            ],
            bases=('prueba.persona',),
        ),
    ]
