# Generated by Django 4.2.3 on 2023-07-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0004_alter_persona_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_Inscripcion', models.CharField(max_length=50)),
                ('fecha_Inscripcion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JugadorInscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
