# Generated by Django 4.2.3 on 2023-07-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0006_delete_estadoinscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado_Inscripcion',
            field=models.CharField(choices=[('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=50),
        ),
    ]
