# Generated by Django 4.2.3 on 2023-07-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0008_competencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('disciplina', models.CharField(choices=[('Futbol', 'Futbol'), ('Baloncesto', 'Baloncesto'), ('Ecuavoly', 'Ecuavoly')], default='Futbol', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
