# Generated by Django 4.2.3 on 2023-07-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0009_arbitro_regla_reglamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoInscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=50)),
                ('estadistica', models.CharField(max_length=50)),
            ],
        ),
    ]
