# Generated by Django 4.2.3 on 2023-07-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0010_equipo_equipoinscrito_temporada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idaYVuelta', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
