# Generated by Django 4.2.3 on 2023-07-13 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0013_alter_marcador_punto_marcador_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='numero_Camiseta',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
