# Generated by Django 4.2.3 on 2023-07-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0014_alter_jugador_numero_camiseta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
