# Generated by Django 4.2.3 on 2023-07-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('EleccionDeRol', models.CharField(blank=True, choices=[('Jugador', 'Jugador'), ('Director Tecnico', 'Director Tecnico'), ('Arbitro', 'Arbitro')], max_length=50, null=True)),
            ],
        ),
    ]
