# Generated by Django 4.2.3 on 2023-07-28 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0002_rename_eleccionderol_persona_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Camiseta', models.PositiveIntegerField()),
                ('persona', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jugadorList', to='dawnbem.persona')),
            ],
        ),
    ]
