# Generated by Django 4.2.3 on 2023-07-28 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0003_jugador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='persona',
        ),
        migrations.AddField(
            model_name='persona',
            name='jugadores',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='personaList', to='dawnbem.jugador'),
        ),
    ]
