# Generated by Django 4.2.3 on 2023-07-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0004_remove_jugador_persona_persona_jugadores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='jugadores',
            new_name='jugador',
        ),
    ]
