# Generated by Django 4.2.3 on 2023-07-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0005_rename_jugadores_persona_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
