# Generated by Django 4.2.3 on 2023-07-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0008_persona_arbitro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='nombre',
        ),
    ]
