# Generated by Django 4.2.3 on 2023-07-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0010_remove_arbitro_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='arbitro',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='jugador',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre',
        ),
        migrations.AddField(
            model_name='persona',
            name='EscogerModalidad',
            field=models.CharField(blank=True, choices=[('Grupal', 'Grupal'), ('Individual', 'Individual')], max_length=50, null=True),
        ),
    ]
