# Generated by Django 4.2.3 on 2023-07-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0011_remove_persona_apellido_remove_persona_arbitro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('EscogerDeporte', models.CharField(blank=True, choices=[('Futbol', 'Futbol'), ('Basquet', 'Basquet'), ('Voley', 'Voley'), ('Otro', 'Otro')], max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Arbitro',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
