# Generated by Django 4.2.3 on 2023-07-29 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0012_requisito_delete_arbitro_delete_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Camiseta', models.PositiveIntegerField()),
                ('ModoJuegoIndividual', models.CharField(blank=True, choices=[('Eliminacion Simple', 'Eliminacion Simple'), ('Rondas de Clasificacion', 'Rondas de Clasificacion'), ('Puntuacion Acumulativa', 'Puntuacion Acumulativa'), ('Uno contra Uno', 'Uno contra Uno')], max_length=50, null=True)),
                ('requisito', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requisitoList', to='dawnbem.requisito')),
            ],
        ),
    ]
