# Generated by Django 4.2.3 on 2023-07-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0014_rename_modojuegoindividual_jugador_modo_juego_individual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='requisito',
        ),
    ]
