# Generated by Django 4.2.3 on 2023-07-29 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0015_remove_jugador_requisito'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='requisito',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jugadorList', to='dawnbem.requisito'),
        ),
    ]
