# Generated by Django 4.2.3 on 2023-07-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0016_jugador_requisito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('EscogerModalidad', models.CharField(choices=[('Grupal', 'Grupal'), ('Individual', 'Individual')], max_length=50)),
                ('EscogerDeporte', models.CharField(choices=[('Futbol', 'Futbol'), ('Basquet', 'Basquet'), ('Voley', 'Voley'), ('Otro', 'Otro')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='requisito',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.DeleteModel(
            name='Requisito',
        ),
    ]
