# Generated by Django 4.2.3 on 2023-07-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0017_registro_remove_jugador_requisito_delete_persona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EleccionDeRol', models.CharField(choices=[('Jugador', 'Jugador'), ('Director Tecnico', 'Director Tecnico'), ('Arbitro', 'Arbitro')], max_length=50)),
            ],
        ),
    ]
