# Generated by Django 4.2.3 on 2023-07-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0019_jugador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='Registro',
            new_name='registro',
        ),
    ]
