# Generated by Django 4.2.3 on 2023-07-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0020_rename_registro_jugador_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Inscripcion', models.DateField()),
                ('fecha_Aprobacion', models.DateField()),
                ('fecha_Rechazo', models.DateField(blank=True, null=True)),
                ('jugador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jugadorList', to='dawnbem.jugador')),
            ],
        ),
    ]
