# Generated by Django 4.2.3 on 2023-07-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0021_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estado_Inscripcion',
            field=models.CharField(blank=True, choices=[('Registrado', 'Registrado'), ('En Proceso', 'En Proceso'), ('Anulada', 'Anulada')], max_length=10, null=True),
        ),
    ]
