# Generated by Django 4.2.3 on 2023-07-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0022_inscripcion_estado_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_Aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_Inscripcion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
