# Generated by Django 4.2.3 on 2023-07-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0026_registro_otro_alter_registro_escogerdeporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='otro',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
