# Generated by Django 4.2.3 on 2023-07-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0028_alter_registro_otro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='otro',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
