# Generated by Django 4.2.3 on 2023-07-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0029_alter_registro_otro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='otro',
        ),
        migrations.AlterField(
            model_name='registro',
            name='EscogerDeporte',
            field=models.CharField(choices=[('Futbol', 'Futbol'), ('Basquet', 'Basquet'), ('Voley', 'Voley'), (models.CharField(blank=True, default=None, max_length=50, null=True), models.CharField(blank=True, default=None, max_length=50, null=True))], max_length=50),
        ),
    ]
