# Generated by Django 4.2.3 on 2023-07-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0030_remove_registro_otro_alter_registro_escogerdeporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='EscogerDeporte',
            field=models.CharField(choices=[('Futbol', 'Futbol'), ('Basquet', 'Basquet'), ('Voley', 'Voley')], default='FUTBOL', max_length=50),
        ),
    ]
