# Generated by Django 4.2.3 on 2023-07-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0034_remove_registro_eleccionderol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='EleccionDeRol',
            field=models.CharField(blank=True, choices=[('Jugador', 'Jugador'), ('Director Tecnico', 'Director Tecnico'), ('Arbitro', 'Arbitro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='EscogerDeporte',
            field=models.CharField(blank=True, choices=[('Futbol', 'Futbol'), ('Basquet', 'Basquet'), ('Voley', 'Voley')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='EscogerModalidad',
            field=models.CharField(blank=True, choices=[('Grupal', 'Grupal'), ('Individual', 'Individual')], max_length=10, null=True),
        ),
    ]
