# Generated by Django 4.2.3 on 2023-07-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0038_equipo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad_maxima_equipos', models.PositiveIntegerField()),
                ('nombre_equipo_local', models.CharField(max_length=50)),
                ('nombre_equipo_visitante', models.CharField(max_length=50)),
            ],
        ),
    ]
