# Generated by Django 4.2.3 on 2023-07-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0039_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='dawnbem.grupo'),
        ),
    ]
