# Generated by Django 4.2.3 on 2023-07-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0041_grupo_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('numero_encuentro', models.PositiveIntegerField()),
                ('estado', models.CharField(blank=True, choices=[('Finalizado', 'Finalizado'), ('Aplazado', 'Aplazado'), ('Suspendido', 'Suspendido'), ('Iniciado', 'Iniciado'), ('Entretiempo', 'Entretiempo')], max_length=20, null=True)),
                ('grupo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='GrupoList', to='dawnbem.grupo')),
            ],
        ),
    ]
