# Generated by Django 4.2.3 on 2023-07-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0042_partido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='grupo',
        ),
        migrations.AddField(
            model_name='partido',
            name='grupo',
            field=models.ManyToManyField(blank=True, related_name='partidos', to='dawnbem.grupo'),
        ),
    ]
