# Generated by Django 4.2.3 on 2023-07-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0045_marcador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='Equipo',
        ),
        migrations.AddField(
            model_name='grupo',
            name='Equipo',
            field=models.ManyToManyField(blank=True, related_name='grupos', to='dawnbem.equipo'),
        ),
    ]
