# Generated by Django 4.2.3 on 2023-07-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0046_remove_grupo_equipo_grupo_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('Equipo', models.ManyToManyField(blank=True, related_name='temporadas', to='dawnbem.equipo')),
            ],
        ),
    ]
