# Generated by Django 4.2.3 on 2023-07-30 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0047_temporada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporada',
            old_name='Equipo',
            new_name='EquipoList',
        ),
    ]
