# Generated by Django 4.2.3 on 2023-07-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0048_rename_equipo_temporada_equipolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='ModoJuego',
            field=models.CharField(blank=True, choices=[('Eliminacion simple', 'Eliminacion simple'), ('Rondas de Clasificacion', 'Rondas de Clasificacion'), ('Puntuacion Acumulativa', 'Puntuacion Acumulativa'), ('Uno contra Uno', 'Uno contra Uno'), ('Ligas', 'Ligas'), ('Fase de Grupos', 'Fase de Grupos'), ('Eliminatorias', 'Eliminatorias')], max_length=50, null=True),
        ),
    ]
