# Generated by Django 4.2.3 on 2023-07-30 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0050_reglamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reglamento',
            name='Temporada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='dawnbem.temporada'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='EquipoList',
            field=models.ManyToManyField(blank=True, default=None, related_name='temporadas', to='dawnbem.equipo'),
        ),
    ]
