# Generated by Django 4.2.3 on 2023-08-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0055_alter_regla_descripcion_alter_reglamento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
