# Generated by Django 4.2.3 on 2023-08-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0057_equipo_grupolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='grupoList',
        ),
    ]
