# Generated by Django 4.2.3 on 2023-08-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0058_remove_equipo_grupolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='grupo',
        ),
    ]
