# Generated by Django 4.2.3 on 2023-08-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0059_remove_partido_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='Equipo',
            field=models.ManyToManyField(blank=True, related_name='sorteos', to='dawnbem.equipo'),
        ),
    ]
