# Generated by Django 4.2.3 on 2023-08-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0060_sorteo_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='fecha_Inscripcion',
            new_name='fecha_solicitud',
        ),
    ]
