# Generated by Django 4.2.3 on 2023-08-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0061_rename_fecha_inscripcion_inscripcion_fecha_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstadoInscripcion', models.CharField(blank=True, choices=[('Registrado', 'Registrado'), ('En Proceso', 'En Proceso'), ('Anulada', 'Anulada')], max_length=10, null=True)),
                ('fecha_Aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_Rechazo', models.DateField(blank=True, null=True)),
                ('Inscripcion', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='EstadoInscripcionList', to='dawnbem.inscripcion')),
            ],
        ),
    ]
