# Generated by Django 4.2.3 on 2023-08-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0062_estadoinscripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstadoInscripcion',
            new_name='RevisionInscripcion',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='estado_Inscripcion',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='fecha_Aprobacion',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='fecha_Rechazo',
        ),
    ]
