# Generated by Django 4.2.3 on 2023-08-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0065_rename_inscripcion_list_equipo_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='regla',
            name='nombre_regla',
            field=models.CharField(default='Sin nombre', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regla',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
