# Generated by Django 4.2.3 on 2023-08-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0068_remove_reglamento_temporada_reglamento_regla_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='regla',
            name='reglamento_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='reglas', to='dawnbem.reglamento'),
        ),
    ]
