# Generated by Django 4.2.3 on 2023-08-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0069_regla_reglamento_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='nombre_equipo_local',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='nombre_equipo_visitante',
        ),
        migrations.RemoveField(
            model_name='regla',
            name='reglamento_list',
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(default='Sin definir', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_local', to='dawnbem.equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_visitante',
            field=models.ForeignKey(default='Sin definir', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_visitante', to='dawnbem.equipo'),
            preserve_default=False,
        ),
    ]
