# Generated by Django 4.2.3 on 2023-08-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0070_remove_grupo_nombre_equipo_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='equipo_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='equipo_visitante',
        ),
    ]
