# Generated by Django 4.2.3 on 2023-08-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0072_partido_equipo_local_partido_equipo_visitante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='Equipo',
            new_name='EquipoList',
        ),
    ]
