# Generated by Django 4.2.3 on 2023-08-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0073_rename_equipo_grupo_equipolist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sorteo',
            old_name='Equipo',
            new_name='Equipo_list',
        ),
    ]
