# Generated by Django 4.2.3 on 2023-08-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0078_alter_inscripcion_estadoinscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='equipos_locales',
            field=models.ManyToManyField(blank=True, related_name='sorteos_locales', to='dawnbem.equipo'),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='equipos_visitantes',
            field=models.ManyToManyField(blank=True, related_name='sorteos_visitantes', to='dawnbem.equipo'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='EstadoInscripcion',
            field=models.CharField(choices=[('Registrado', 'Registrado'), ('En Proceso', 'En Proceso'), ('Anulada', 'Anulada')], default='En Proceso', max_length=10),
        ),
    ]
