# Generated by Django 4.2.3 on 2023-08-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0079_sorteo_equipos_locales_sorteo_equipos_visitantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='equipos',
            field=models.ManyToManyField(to='dawnbem.equipo'),
        ),
        migrations.AlterField(
            model_name='regla',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
