# Generated by Django 4.2.3 on 2023-08-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0084_partido_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dawnbem.grupo'),
            preserve_default=False,
        ),
    ]
