# Generated by Django 4.2.3 on 2023-08-14 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0085_partido_grupo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RevisionInscripcion',
        ),
    ]
