# Generated by Django 4.2.3 on 2023-08-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0087_calendario_tipocalendario_remove_partido_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='EscogerDeporte',
            field=models.CharField(blank=True, choices=[('Futbol', 'Futbol'), ('Ping Pong', 'Ping Pong')], max_length=10, null=True),
        ),
    ]
