# Generated by Django 4.2.3 on 2023-08-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawnbem', '0088_alter_registro_escogerdeporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(blank=True, choices=[('Finalizado', 'Finalizado'), ('Aplazado', 'Aplazado'), ('Suspendido', 'Suspendido'), ('Iniciado', 'Iniciado'), ('Entretiempo', 'Entretiempo'), ('No Iniciado', 'No Iniciado')], default='No Iniciado', max_length=20, null=True),
        ),
    ]
